name = "cfllm"
main = "src/index.ts"
compatibility_date = "2024-03-18"
minify = true

routes = [
  { pattern = "cfllm.palettetool.com/*", zone_name = "palettetool.com" }
]

# Secrets should be set via `wrangler secret put`
# DISCORD_PUBLIC_KEY
# DISCORD_BOT_TOKEN
# DISCORD_APPLICATION_ID

[ai]
binding = "AI"

[vars]
# Default provider can be overridden per environment
LLM_PROVIDER = "gemini"

[[d1_databases]]
binding = "GUILDS_DB"
database_name = "guilds-db"
database_id = "52bfc497-1ad5-4c31-bc8e-8210322837b9"
