name = "cfllm"
main = "src/index.ts"
compatibility_date = "2024-03-18"

routes = [
  { pattern = "cfllm.palettetool.com/*", zone_name = "palettetool.com" }
]

# Secrets should be set via `wrangler secret put`
# DISCORD_PUBLIC_KEY
# DISCORD_BOT_TOKEN
# DISCORD_APPLICATION_ID

[ai]
binding = "AI"

[vars]
# Default provider can be overridden per environment
LLM_PROVIDER = "gemini"
